name = "lustre_transition"
version = "0.2.0"
description = "Transitions for lustre, designed for use with Tailwind"
target = "javascript"
licenses = ["MIT"]
repository = { type = "github", user = "codemonkey76", repo = "lustre_transition" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
lustre = ">= 4.3.0 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
